Implement Prototype
devinit/grand-bargain-monitoring pull request #1
Opened 2017-03-28 14:15 UTC by hayfield

This adds a prototype that loads and parses data files, then outputs a multicoloured sortable and searchable table containing data.

2017-03-28 14:49 UTC, dalepotter commented on .gitignore
> +# untracked data
Small point, but could make the comment more descriptive - e.g. `# CSV and data files pulled from a remote source`

2017-03-28 14:53 UTC, dalepotter commented on src/app.py
> +@app.route("/hello")
This route could be deleted!

2017-03-28 15:03 UTC, dalepotter commented on src/parse_data.py
> +
I would suggest being more precise about what type of array is expected in the input params - i.e. a list or set? I don't think the function would work if an associative array was used.

2017-03-28 15:05 UTC, dalepotter commented on src/parse_data.py
> +		A dictionary of dictionaries. The keys in the first-level dictionary are publisher registry IDs. Keys at the second level are names of statistics parsed from data file headers.
Suggest split over multiple lines to reduce line length

2017-03-28 15:05 UTC, dalepotter commented on src/parse_data.py
> +		A dictionary of dictionaries. The keys in the first-level dictionary are publisher registry IDs. Keys at the second level are names of statistics parsed from data file headers.
Same comment as above re line length :-)

2017-03-28 15:10 UTC, hayfield commented on src/parse_data.py
> +
Is `list` specific enough?

2017-03-28 15:12 UTC, dalepotter requested changes
Could we fix up the docstrings as per the comments, particularity to clarify the comment re arrays before we merge?

2017-03-28 15:22 UTC, hayfield commented
@dalepotter Changes made in response to comments.

2017-04-06 09:46 UTC, dalepotter commented
👍  

Looks good to me, thanks for the changes :-)

2017-04-06 09:46 UTC, dalepotter approved these changes

2017-04-06 09:46 UTC, merged